version: 0.0
os: linux
files:
  - source: /
    destination: /home/ec2-user/CodeDeploy
hooks:
  BeforeInstall:
    - location: install.sh
      timeout: 3000
      runas: root
    - location: start_server.sh
      timeout: 300
      runas: root
  ApplicationStop:
    - location: stop_server.sh
      timeout: 300
      runas: root