version: 0.2
phases:
  install:
    commands:
       - echo Running install.sh and pre_install.sh
       - sudo ./pre_install.sh
       - sudo ./install.sh
artifacts:
  files:
     - '**/*' #copy all build files to S3 location